<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Da wedding page</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <style>
            body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 18px;
            }

            h1 {
                color: #719e40;
                letter-spacing: -3px;
                font-family: 'Lato', sans-serif;
                font-size: 100px;
                font-weight: 200;
                margin-bottom: 0;
            }
            img {
              max-width: 60%;
            }
        </style>
    </head>
    <body>
      <?php
        if (isset($post['password']) && $post['password'] === 'awa awa') {
       ?>
        <h1>Nivell 15</h1>
        <img src="../assets/imatges/nivell15.jpg" />
        <form action="16" method="post">
          <input id="pwd" type="text" name="password"/>
        </form>
      <?php
    } else {
       ?>
       <h1>Pero que esteu fent?!?!?</h1>
       <p> sigui el que sigui, sembla que així no funciona</p>
       <?php
     }
        ?>



        <!--empresa que podríem haver muntat...-->        
    </body>
</html>